resources:
- ../bases/
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-api@sha256:d35dcc1376c852cc41e65096bd72830b58ea1361d0e6ead00fd90b58db487a20
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:8365c23c9d83c6bf768d823145b63dc2d49802277557e2c79d9e2019996f6906
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:8365c23c9d83c6bf768d823145b63dc2d49802277557e2c79d9e2019996f6906
  target:
    kind: Deployment
    name: controller-manager