resources:
- ../bases/
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-api@sha256:005ef2c90ef3e0d852004509abfecdf9045c4e31135bf6a92e4979940f87bab0
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:f38e304131749c9d5959d57f1be20e6af960e135e6869a06576bb161fe073ac2
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:f38e304131749c9d5959d57f1be20e6af960e135e6869a06576bb161fe073ac2
  target:
    kind: Deployment
    name: controller-manager